
sudo: required

# safelist
branches:
  only:
  - master
  - integration

language: python
python:
  - "3.6"

cache: pip

services:
  - docker # required, but travis uses older version of docker :(

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}

script:
  - docker --version
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; elif [ "$TRAVIS_BRANCH" == "integration" ]; then bash <(curl https://raw.githubusercontent.com/KenSciML/InternalTools/ci-tools/increment_version.sh?token=AEwy07AxYEiyUfwEr-VhJsirAA_W9Vebks5ZXBDwwA%3D%3D) -p "$(<VERSION)"  ; else echo $TRAVIS_BRANCH ; fi`
  - echo $TAG

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "integration" ]; git add -u ; git checkout integration ; echo $TAG > VERSION ; git add VERSION ; git commit -m "[Travis-CI] Build $TRAVIS_BUILD_NUMBER [ci skip]" ; git push ; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; git add -u ; git checkout master ; git commit -m "[Travis-CI] Build $TRAVIS_BUILD_NUMBER [ci skip]" ; git push ; fi
  - echo "$(<VERSION)"
  - echo "$TRAVIS_PULL_REQUEST"
  - echo "$TRAVIS_BRANCH"
